### ISSUE TITLE
Development Server Error: 500

### ISSUE THREAD

**Issue by yashvekaria** [vincee48/react-native-checkbox-field#1]
After implementing the CheckboxField  as per suggested guide, I am facing such issue. Can you tell what I have done wrong.

![error](https://cloud.githubusercontent.com/assets/5152954/14640339/b7d69b3e-065e-11e6-9223-c285f052bba0.png)

**Comment by vincee48** [comment]
The package itself does not use the spread operator, so it may potentially be resolved by adding --reset-cache flag when starting the development server.

Otherwise, could you please advise which version of React Native you are running? Also, if you are using a .babelrc file, is "react-native" a preset in it?

**Comment by vincee48** [comment]
I have updated the package to remove some dependencies and updated React + React Native versions. Please update to the latest version and let me know if you still have the issue.
